### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by bradbarrish** [sindresorhus/quickgpt-meta#3]
Hi Sindre. I recently downloaded QuickGPT and I am not able to get anything to happen when I click on the OpenAI Log In button that you see when you open the app for the first time. When I double-click, I get an error and when I click on the Log In button on the resulting screen, it takes me back to the initial screen I see when I open QuickGPT. I've attached a screen recording so you can see what's happening. Thanks for your work and for your help with this issue. 

https://user-images.githubusercontent.com/615100/235239918-1cece108-82c9-4ab9-b01b-e7bf09c932f6.mov

**Comment by sindresorhus** [comment]
It sometimes takes a while after clicking "Log in" for it to acutally go to the login. Make sure you give it some time.

Can you try launching the app while pressing `Shift+Control+Option+Command` and see if it helps to delete the app data?

**Comment by sindresorhus** [comment]
If that does not work, can you try this special build and let me know if there are any errors in the devtools console tab after you try to log in?

[QuickGPT.app.zip](https://github.com/sindresorhus/quickgpt-meta/files/11358784/QuickGPT.app.zip)
