### ISSUE TITLE
feat: Dark mode toggle

### ISSUE THREAD

**Issue by pythoninthegrass** [sindresorhus/quickgpt-meta#6]
Sooo sorry if I didn't find this first, but sent you a couple emails through the app just now.

Looking to get a dark mode toggle exposed in the settings for a permanent theme change that may differ from the system theme settings.

Not a swifty, but know enough frontend to be dangerous. Happy to take a look at the source code if you'd like 👌 

## Current Settings (sans Dark mode toggle)
![Screenshot 2024-04-30 at 1 47 20 PM](https://github.com/sindresorhus/quickgpt-meta/assets/4097471/7b2a4b0e-d4f4-4a23-889c-b7af96ff243d)

## Native CSS capability
![Screenshot 2024-04-30 at 1 43 09 PM](https://github.com/sindresorhus/quickgpt-meta/assets/4097471/c825e82f-f903-411a-9bef-6bbed8fcf343)

**Comment by sindresorhus** [comment]
Added in the latest update. Just click "Check for Updates" in the app.

**Comment by pythoninthegrass** [comment]
Thanks so much @sindresorhus ! Works perfectly 🙏
